### ISSUE TITLE
support for script-inserted scripts

### ISSUE THREAD

**Issue by msridhar** [Berkeley-Correctness-Group/Jalangi-Berkeley#3]
First off, thanks for creating the custom Firefox build for Mac!  I had excellent success getting it up and running.  

I'm seeing a case where a script-inserted script is not getting instrumented.  The site I'm trying to instrument is http://manu.sridharan.net.  The end of the page has the standard Google Analytics stub script as an inline script:

``` javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44414635-1', 'sridharan.net');
  ga('send', 'pageview');
```

This injects a `<script src="//www.google-analytics.com/analytics.js" async=""></script>` node into the DOM.  I added `r'google-analytics.com'` to my included list in `instrumentFF.py`, but I still don't see `analytics.js` being instrumented.  I don't even see the corresponding call to `instrumentFF.py` on the command line.  Are script-inserted scripts currently handled by the custom Firefox build? /cc @ksen007

**Comment by NF997** [comment]
Hi,  @msridhar 

I'm playing around with Jalangi, because I will soon give a presentation about TypeDevil in a seminar at the TU Munich.
I am able to analyze files locally, but unfortunately I can not reproduce the In-browser instrumentation with InstrumentFF.
I am also working on macOS.
I followed every step described by the README, but when I open Firefox (Nightly) and browse to a page, no folder called `instrumentFF_tmp` appears.
Since you were able to get the In-browser instrumentation up and running, do you have any clues for me?
Did you also just grab the custom firefox version from the README, added instrumentFF to your PATH environment variable and modified the `scripts/instrumentFF.py` accordingly?
Any ideas what could be wrong with my setup?

Greetings from Munich and thanks in advance!

**Comment by msridhar** [comment]
@NF997 this was quite a long time ago.  I don't remember exactly what I did.  Maybe @michaelpradel or @JacksonGL can help more

**Comment by JacksonGL** [comment]
@NF997 It worked for me a few years ago. One way to troubleshoot the problem on your local machine is to manually instrument the [patch file](http://mp.binaervarianz.de/jalangi/firefox_jalangi_20140815.diff) of the firefox browser and see if the following code is executed:
```
+    // call instrumenter
+    string cmd = "instrumentFF";
+    cmd = cmd + " " + fileNameOrig + " " + fileNameInstr;
+    cmd = cmd + " eval_code.js";
+    int ret =  system(cmd.c_str());
```
If the ```instrumentFF.py``` script is invoked, manually instrument and check if the following code in [instrumentFF.py](https://github.com/Berkeley-Correctness-Group/Jalangi-Berkeley/blob/3f3d6d2090253892bce67423c54a8a400aed410b/scripts/instrumentFF.py) is invoked:
```python
  workingDir = os.path.dirname(workingDirName) 
  if not os.path.exists(workingDir):
    os.makedirs(workingDir)
```
```workingDirName``` contains the path to the "instrumentFF_tmp" folder

**Comment by NF997** [comment]
@JacksonGL 
Thanks for the quick response.
Unfortunately I haven't yet understood how to "apply the patch against the Mozilla code base".
Could you please share a resource explaining this process?

**Comment by michaelpradel** [comment]
What Liang means is that you could build your own version of Firefox from the Mozilla Firefox code repositoty, as described briefly in the README:
"Build it yourself by applying this patch against revision c6fc35c53c37 of the Mozilla code base". 

However, if your purpose is "only" to play a bit with TypeDevil and its abilities, it might be easier to just run the non-browser version of the analysis.

**Comment by NF997** [comment]
@michaelpradel 
I read the README, but unfortunately the sentence you cited is just too abstract for me. I don't know what concrete steps are required to build my own custom Firefox version. Are there any resources out there which describe this process?

Also interesting:
When executing the /Jalangi-Berkeley/scripts/path_unix/instrumentFF "manually", I get the following console output:
`python: can't open file 'scripts/instrumentFF.py': [Errno 2] No such file or directory`
Of course the file /Jalangi-Berkeley/scripts/instrumentFF.py exists, since I didn't mess around with the folder structure after cloning the repo. Any ideas?

I know that you can't play technical support for a student who tries to get your old code to run, but it would be pretty cool to be able to give a little "live demo" (based on a real world web app) of TypeDevil in my upcoming presentation.

**Comment by michaelpradel** [comment]
Did you run Firefox from the Jalangi-Berkeley directory? If not, then please try. The error message sounds like that's the problem.

**Comment by NF997** [comment]
I am opening Firefox with `open /Applications/Nightly.app` from the `Jalangi-Berkeley` directory and it doesn't work.
But you were right. When I executed the `/Jalangi-Berkeley/scripts/path_unix/instrumentFF` "manually", I wasn't in the `Jalangi-Berkeley` directory.
Do you have any other ideas what could go wrong?
Where should the `instrumentFF_tmp` directory be located?
Can I get any information about instrumentFF out of Firefox directly?

**Comment by michaelpradel** [comment]
Try running Firefox with the --new-instance option. It seems that your instance of Firefox isn't really running from the Jalangi-Berkeley directory, possibly because you already have another instance of Firefox running.

**Comment by NF997** [comment]
Unfortunately, `open -a /Applications/Nightly.app -n -F` from the `Jalangi-Berkeley` directory didn't work, either. The `instrumentFF_tmp` directory just doesn't appear.
Is there another way to start Firefox from the CL?

**Comment by NF997** [comment]
@michaelpradel 
I could finally manage to run Firefox the right way.
For whatever reasons, it doesn't work with the `open` command, but executing `/Applications/Nightly.app/Contents/MacOS/firefox` "directly" worked just fine. Now I got the `instrumentFF_tmp` directory with plenty of files in it.
However, I get the following warning in the console multiple times, although the install script ran without errors.

```
module.js:341
    throw err;
    ^

Error: Cannot find module 'esprima'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at /Users/nicofechtner/DEV/Jalangi-Berkeley/src/js/analyses/inconsistentType/Preprocessor.js:22:19
    at Object.<anonymous> (/Users/nicofechtner/DEV/Jalangi-Berkeley/src/js/analyses/inconsistentType/Preprocessor.js:225:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

I am using Node v0.10.3 which should work properly according to the README.
Any ideas what could be the root cause of this errors?

**Comment by michaelpradel** [comment]
You need to install esprima with "npm install esprima".

**Comment by NF997** [comment]
Thanks for your help so far!
Indeed, i had to install `esprima` and `escodegen`.
Now I have all the instrumented files in the `instrumentFF_tmp` directory, but where can I find the results of the TypeDevil Analysis? 
Of course, I uncommented the following in the `instrumentFF.py`:

``` python
jalangiAnalysisFiles = [ 
  jalangiBerkeleyBaseDir+"src/js/analyses/CommonUtil.js",
  jalangiBerkeleyBaseDir+"src/js/analyses/inconsistentType/TypeUtil.js",
  jalangiBerkeleyBaseDir+"src/js/analyses/inconsistentType/BenchmarkHelper.js",
  jalangiBerkeleyBaseDir+"src/js/analyses/inconsistentType/CallGraph.js",
  jalangiBerkeleyBaseDir+"src/js/analyses/inconsistentType/FilterAndMerge.js",
  jalangiBerkeleyBaseDir+"src/js/analyses/inconsistentType/TypeAnalysis.js",
  jalangiBerkeleyBaseDir+"src/js/analyses/inconsistentType/InconsistentTypeEngine.js"
]
```

Nevertheless, I am not shure where to find the results of the analysis.

I am looking for output similar to what you get when running `./scripts/inconsistent_type_analysis.sh tests/inconsistentType/inconsistent_paper.js`.

**Comment by michaelpradel** [comment]
I'm not 100% sure anymore: Either there is a analysisResults.json file
in the current working directory or the results are written to the
browser/web console.

**Comment by NF997** [comment]
There is no `analysisResults.json` file.
In the browser console I don't get any valuable output, too.
Instead, I get a lot of `"analysis exception!!!"` outputs.
Any ideas?

**Comment by michaelpradel** [comment]
This means something when wrong during the analysis, which could be for many reasons. Does it also happen with a minimal website that does nothing but loading a minimal JavaScript file?

**Comment by NF997** [comment]
@michaelpradel 
I set up a minimal website which does nothing but executing the example you use through out your paper:

``` html
<!doctype html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Test TypeDevil</title>
</head>

<body>
    <script>
        function addWrapped(x, y) {
            if (y) {
                return x.v + y.v;
            } else {
                return x.v;
            }
        }
        function Wrapper(v) {
            this.v = v;
        }
        console.log(addWrapped({ v: 23 }));
        console.log(addWrapped({ v: 20 }, new Wrapper(3)));
        console.log(addWrapped({ v: "18" }, new Wrapper(5)));
    </script>
</body>

</html>
```

You can find the site here: [http://laughing-darwin-2365ec.bitballoon.com/](http://laughing-darwin-2365ec.bitballoon.com/)
I the started the analysis with `/Applications/Nightly.app/Contents/MacOS/firefox http://laughing-darwin-2365ec.bitballoon.com`.
Unfortunately, there is neither a `analysisResults.json`, nor are the results written to the browser console, nor to the bash. Here is the bash output:

```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
instrumentFF.py called with: ['scripts/instrumentFF.py', '--checkURL', 'self-hosted'] 
Will not instrument self-hosted
2018-06-02 08:11:01.509 firefox[41326:3196579] *** WARNING: Method userSpaceScaleFactor in class NSWindow is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
instrumentFF.py called with: ['scripts/instrumentFF.py', '--checkURL', 'self-hosted'] 
Will not instrument self-hosted
instrumentFF.py called with: ['scripts/instrumentFF.py', '--checkURL', 'self-hosted'] 
Will not instrument self-hosted
instrumentFF.py called with: ['scripts/instrumentFF.py', '--checkURL', 'http://laughing-darwin-2365ec.bitballoon.com/'] 
Will instrument http://laughing-darwin-2365ec.bitballoon.com/
Instrumenting JavaScript code of length 288 from file http://laughing-darwin-2365ec.bitballoon.com/ (JS::Evaluate).
instrumentFF.py called with: ['scripts/instrumentFF.py', '--firstTime', 'instrumentFF_tmp_orig.js', 'instrumentFF_tmp_instr.js', 'http://laughing-darwin-2365ec.bitballoon.com/'] 
tmpOrig: instrumentFF_tmp_orig.js
tmpInstr: instrumentFF_tmp_instr.js
Searching cached file for httplaughing-darwin-2365ec.bitballoon.com.js
.. Nothing found
To beautify source code before instrumentation, install js-beautify.
Calling Jalangi instrumenter with
node /Users/nicofechtner/DEV/Jalangi-Berkeley//../jalangi//src/js/instrument/esnstrument.js --dirIIDFile /Users/nicofechtner/DEV/Jalangi-Berkeley/instrumentFF_tmp/ --noInstrEval --inlineIID /Users/nicofechtner/DEV/Jalangi-Berkeley/instrumentFF_tmp/httplaughing-darwin-2365ec.bitballoon.com.js
Adding lib /Users/nicofechtner/DEV/Jalangi-Berkeley/src/js/analyses/CommonUtil.js
Adding lib /Users/nicofechtner/DEV/Jalangi-Berkeley/src/js/analyses/inconsistentType/TypeUtil.js
Adding lib /Users/nicofechtner/DEV/Jalangi-Berkeley/src/js/analyses/inconsistentType/BenchmarkHelper.js
Adding lib /Users/nicofechtner/DEV/Jalangi-Berkeley/src/js/analyses/inconsistentType/CallGraph.js
Adding lib /Users/nicofechtner/DEV/Jalangi-Berkeley/src/js/analyses/inconsistentType/FilterAndMerge.js
Adding lib /Users/nicofechtner/DEV/Jalangi-Berkeley/src/js/analyses/inconsistentType/TypeAnalysis.js
Adding lib /Users/nicofechtner/DEV/Jalangi-Berkeley/src/js/analyses/inconsistentType/InconsistentTypeEngine.js
instrumentFF.py called with: ['scripts/instrumentFF.py', '--checkURL', 'self-hosted'] 
Will not instrument self-hosted
^C
```

I also have a general question about the use of instrumentFF:
When does the dynamic analysis stop? Assuming that i click around on a complex site, when does the analysis decide to stop and e.g. build the type graph? Or is the type graph builded "on the fly" and updated every time new type observations are gathered?

**Comment by michaelpradel** [comment]
The in-browser analysis stops and logs its results when the "beforeunload" event gets fired. Unfortunately, I don't have time to further help with debugging this issue. If you want to play with the analysis, the best way will be to use the non-browser version, which is easier to use. Thanks for giving it a try!
